catalogo/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    # path('chat/', include('conversation.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:conversation_id>/', views.detail, name='detail'),
    path('new/<int:item_id>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import Loginform

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'), 
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=Loginform), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
] 

core/models.py
from django.db import models

# Create your models here.
class contactParm(models.Model):
    product_contact_whatsapp_phone = models.CharField(max_length=16)
    product_contact_whatsapp_text = models.TextField()

    class Meta:
        verbose_name_plural = 'contactParms'
    
    def __str__(self) -> str:
        return self.product_contact_whatsapp_phone

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class Loginform(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nome de usuário',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Senha',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nome de usuário',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'exemplo@email.com',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ao menos 1 letra maiúscula, número e símbolo. Exemplo: Rei@2023',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirme a senha',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm
from core.models import contactParm


def index(request):
    items_ = Item.objects.filter(is_sold=False).order_by('?')[:9]

    items = [items_[i:i+3] for i in range(0, len(items_), 3)]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def contact(request):
    whatsapp = contactParm.objects.first()
    whatsapp_number = whatsapp.product_contact_whatsapp_phone
    whatsapp_link = f'https://api.whatsapp.com/send?phone={whatsapp.product_contact_whatsapp_phone}&text=Olá, vim pelo Marketplace :)'

    return render(request, 'core/contact.html', {
        'whatsapp_link': whatsapp_link,
        'whatsapp_number': whatsapp_number
    })

def signup(request):

    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:

        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/contact.html
{% extends "core/master.html" %}
{% load static %}
{% block title %}
  Contato
{% endblock title %}
{% block content %}
  <div class="mt-6 px-3 md:px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-6 text-2xl text-center">Contato</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <a href="https://www.linkedin.com/in/giovani-drosda-lima/"
         target="_blank"
         rel="noopener noreferrer">
        <div class="rounded-xl w-full flex justify-start bg-gray-200">
          <div class="h-16 w-16 md:h-32 md:w-32">
            <img src="{% static "linkedin.png" %}" class="h-full" />
          </div>
          <div class="flex items-center justify-center grow">
            <h1 class="text-xl md:text-3xl text-center">Giovani Drosda</h1>
          </div>
        </div>
      </a>
      <a href="https://www.instagram.com/dev_com_cafe/"
         target="_blank"
         rel="noopener noreferrer">
        <div class="rounded-xl w-full flex justify-start bg-gray-200">
          <div class="h-16 w-16 md:h-32 md:w-32">
            <img src="{% static "instagram.png" %}" class="h-full" />
          </div>
          <div class="flex items-center justify-center grow">
            <h1 class="text-xl md:text-3xl text-center">@dev_com_cafe</h1>
          </div>
        </div>
      </a>
      <a href="{{ whatsapp_link }}" target="_blank" rel="noopener noreferrer">
        <div class="rounded-xl w-full flex justify-start bg-gray-200">
          <div class="h-16 w-16 md:h-32 md:w-32">
            <img src="{% static "whatsapp.png" %}" class="h-full" />
          </div>
          <div class="flex items-center justify-center grow">
            <h1 class="text-xl md:text-3xl text-center">{{ whatsapp_number }}</h1>
          </div>
        </div>
      </a>
      <a href="mailto:gdrosdalima@gmail.com"
         target="_blank"
         rel="noopener noreferrer">
        <div class="rounded-xl w-full flex justify-start bg-gray-200">
          <div class="h-16 w-16 md:h-32 md:w-32">
            <img src="{% static "gmail.png" %}" class="h-full" />
          </div>
          <div class="flex items-center justify-center grow">
            <h1 class="text-xl md:text-3xl text-center">gdrosdalima@gmail.com</h1>
          </div>
        </div>
      </a>
    </div>
  </div>
  {% endblock content %}

core/templates/core/index.html
{% extends "core/master.html" %}
{% load static %}
{% block title %}
  Bem vindo
{% endblock title %}
{% block content %}
  <div class="mt-6 px-3 md:px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-6 text-2xl text-center">Produtos recomendados</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
    {% for i in items %}
    <div class="flex flex-col m-4 col-span-1">
      {% for item in i %}
          <div class="bg-white rounded-xl col-span-1 m-4">
            <a href="{% url 'item:detail' item.id %}">
              <div>
                <img src="{{ item.image_url }}"
                     {% comment %} onerror="this.src='https://http.cat/404';" {% endcomment %}
                     onerror="this.src='{% static "lupa.png" %}';"
                     class="w-full h-auto rounded-t-xl" />
              </div>
              <div class="p-4">
                <h2 class="text-xl">{{ item.name }}</h2>
                <p class="text-gray-500">R$: {{ item.price.amount }}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
    </div>
  </div>
  <div class="mt-6 px-3 md:px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-6 text-2xl text-center">Categorias:</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      {% for category in categories %}
        <div class="bg-white rounded-xl">
          <a href="{% url 'item:items' %}?category_id={{ category.id }}">
            <div class="p-4">
              <h2 class="text-xl">{{ category.name }}</h2>
              <p class="text-gray-500">{{ category.items.count }} produtos</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

core/templates/core/login.html
{% extends "core/master.html" %}
{% block title %}
Login
{% endblock title %}
{% block content %}
    <div class="w-full md:w-1/2 p-6 my-6 md:mx-auto bg-gray-300 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Usuário</label>
                <br />
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Senha</label>
                <br />
                {{ form.password }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}{{ field.errors }}{% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white w-full">Entrar</button>
        </form>
        <p class="m-2">Não tem cadastro? <a href="{% url "core:signup" %}" class="text-teal-700 underline">Registrar</a></p>
    </div>
{% endblock content %}

core/templates/core/master.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A catalogue marketplace demo by Giovani Drosda Lima." />
    <meta name="keywords"
          content="Marketplace, Django, Dev, Catalogue, Shopping, Online" />
    <title>
      {% block title %}
      {% endblock title %}
    | Marketplace</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div class="fixed w-full z-50">
      <nav class="py-2 px-4 md:px-6 flex justify-between items-center bg-gray-50">
        <div class="flex">
          <a href="{% url 'core:index' %}" class="flex items-center">
            <img width="50" height="50" src="https://img.icons8.com/ios/50/shop--v2.png" alt="M" class="mx-2"/>
            <h1 class="text-sm md:text-3xl font-semibold">Marketplace</h1>
            {% if request.user.is_authenticated %}
              <p class="text-sm md:text-3xl font-thin">&nbsp;| {{ request.user.username }}</p>
            {% endif %}
          </a>
        </div>
        <div class="flex text-left space-around gap-4 items-baseline">
          <form method="get" action="{% url 'item:items' %}">
            <div class="flex">
              <input name="item_query"
                     class="py-4 px-6 border border-black md:h-12 hidden md:block rounded-l-xl"
                     type="text"
                     value="{{ item_query }}"
                     placeholder="O que procura?" />
              <button class="w-[2.4em] md:w-16 md:h-12 md:border border-black rounded-r-xl">
                <img src="https://img.icons8.com/ios/50/000000/search--v3.png" alt="Q" />
              </button>
            </div>
          </form>
          {% if not request.user.is_authenticated %}
            <a href="{% url 'core:login' %}"
               class="text-gray-700 hover:bg-gray-100 hover:text-gray-900 md:w-20 self-center">
              <img width="64"
                   height="64"
                   class="w-[2.4em] md:w-12 md:h-12"
                   src="https://img.icons8.com/pastel-glyph/64/user-male-circle.png"
                   alt="Entrar" />
            </a>
          {% endif %}
        </div>
      </nav>
      <nav class="px-4 md:px-6 flex justify-around items-center border-b border-gray-200 bg-gray-50">
        {% if request.user.is_authenticated %}
          <a href="{% url 'item:new' %}"
             class="px-4 py-2 text-base md:text-lg text-gray-700 hover:bg-gray-100 hover:text-gray-900">Novo produto</a>
        {% endif %}
        {% if request.user.is_authenticated %}
          {% comment %}
        <a href="{% url 'conversation:inbox' %}" class="px-4 py-2 text-base md:text-lg text-gray-700 hover:bg-gray-100 hover:text-gray-900">Inbox</a>
          {% endcomment %}
          <a href="{% url 'dashboard:index' %}"
             class="px-4 py-2 text-base md:text-lg text-gray-700 hover:bg-gray-100 hover:text-gray-900">Dashboard</a>
          <a href="{% url 'core:logout' %}"
             class="px-4 py-2 text-base md:text-lg text-gray-700 hover:bg-gray-100 hover:text-gray-900">Sair</a>
        {% endif %}
      </nav>
    </div>
    <div class="px-4 py-4 md:px-6">
      <div class="bg-gray-50 rounded-xl px-2 py-2 mt-12 md:mt-32">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <footer class="py-4 px-4 md:px-6 flex flex-col md:flex-row justify-between bg-gray-800">
      <div class="w-full md:w-2/3 pr-0 md:pr-10 mb-4 md:mb-0">
        <h3 class="mb-2 md:mb-5 font-semibold text-gray-400">Sobre nós</h3>
        <p class="text-base md:text-lg text-gray-500">
          O <strong>Marketplace</strong> é uma plataforma de demonstração, não deve ser utilizada para vendas. A plataforma, entretanto, pode ser facilmente convertida em um marketplace real para sua empresa. Para mais informações, acesse a página de <a href="{% url "core:contact" %}" class="text-teal-700 underline font-semibold">Contato</a>.
        </p>
      </div>
      <div class="w-full md:w-1/3">
        <h3 class="mb-2 md:mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
          <li>
            <a href="#"
               class="text-base md:text-lg text-teal-500 hover:text-teal-700">Sobre</a>
          </li>
          <li>
            <a href="{% url 'core:contact' %}"
               class="text-base md:text-lg text-teal-500 hover:text-teal-700">Contato</a>
          </li>
          <li>
            <a href="#"
               class="text-base md:text-lg text-teal-500 hover:text-teal-700">Política de privacidade</a>
          </li>
          <li>
            <a href="#"
               class="text-base md:text-lg text-teal-500 hover:text-teal-700">Termos de uso</a>
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

core/templates/core/signup.html
{% extends "core/master.html" %}
{% block title %}
    Registrar
{% endblock title %}
{% block content %}
    <div class="w-full md:w-1/2 w-1/2 p-6 my-6 md:mx-auto bg-gray-300 rounded-xl">
        <h1 class="mb-6 text-3xl">Registrar</h1>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Usuário</label>
                <br />
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label>
                <br />
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Senha</label>
                <br />
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Confirme a senha</label>
                <br />
                {{ form.password2 }}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}{{ field.errors }}{% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white w-full">Enviar</button>
        </form>
        <p class="m-2">Já tem cadastro? <a href="{% url "core:login" %}" class="text-teal-700 underline">Entrar</a></p>
    </div>
{% endblock content %}