catalogo/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    # path('chat/', include('conversation.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:conversation_id>/', views.detail, name='detail'),
    path('new/<int:item_id>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import Loginform

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'), 
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=Loginform), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
] 

item/models.py
from django.db import models
from django.contrib.auth.models import User
from djmoney.models.fields import MoneyField

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('name',)
    
    def __str__(self) -> str:
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    briefing = models.CharField(blank=True, null=True, max_length=255)
    # image_url = models.URLField(blank=True, null=True)
    image_url = models.CharField(blank=True, null=True, max_length=1024)

    price = MoneyField(max_digits=10, decimal_places=2, default_currency='BRL')
    is_sold = models.BooleanField(default=False)

    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Items'
    
    def __str__(self) -> str:
        return self.name

item/forms.py
from django import forms
from .models import Item
from django.utils.translation import gettext_lazy as _
from djmoney.forms.widgets import MoneyWidget

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'briefing', 'description', 'price', 'image_url',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'briefing': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': MoneyWidget(attrs={
                'class': INPUT_CLASSES,
            }),
            'image_url': forms.FileInput(),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'briefing', 'description',
                  'price', 'image_url', 'is_sold')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'briefing': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': MoneyWidget(attrs={
                'class': INPUT_CLASSES,
            }),
            'image_url': forms.FileInput(),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Category
from .forms import NewItemForm, EditItemForm
from core.models import contactParm
from catalogo.settings import MEDIA_ROOT, MEDIA_URL
import cloudinary

def items(request):
    item_query = request.GET.get('item_query', '').strip()
    category_id = request.GET.get('category_id', 0)
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    if category_id:
        items = items.filter(category=category_id)

    if item_query:
        items = items.filter(Q(name__icontains=item_query) | Q(description__icontains=item_query))

    return render(request, 'item/items.html', {
        'items': items,
        'categories': categories,
        'item_query': item_query,
        'category_id': int(category_id),
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    whatsapp = contactParm.objects.first()
    text = whatsapp.product_contact_whatsapp_text.replace('&produto', f'{item.name}')
    whatsapp_call_link = f'https://api.whatsapp.com/send?phone={whatsapp.product_contact_whatsapp_phone}&text={text}'

    related_items = Item.objects.filter(category = item.category, is_sold = False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
        'whatsapp_call_link': whatsapp_call_link
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            for filename, file in request.FILES.items():
                result = cloudinary.uploader.upload(file)
                item.image_url = result['secure_url']
                item.save()
                break

            return redirect('item:detail', pk=item.id)

    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    url = item.image_url

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            for filename, file in request.FILES.items():
                form.save(commit=False)
                result = cloudinary.uploader.upload(file)
                item.image_url = result['secure_url']
                item.save()
                break
            else:
                form.save(commit=False)
                item.image_url = url
                item.save()

            return redirect('item:detail', pk=item.id)

    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends "core/master.html" %}
{% load static %}
{% block title %}
  {{ item.name }}
{% endblock title %}
{% block content %}
  <div class="grid grid-cols-5 gap-6">
    <div class="col-span-5 md:col-span-3 flex items-center justify-center">
      <img src="{{ item.image_url }}"
           {% comment %}
           onerror="this.src='https://http.cat/404';"
           {% endcomment %}
           onerror="this.src='{% static "lupa.png" %}';"
           alt="{{ item.name }}"
           class="rounded-xl max-h-[75vh]" />
    </div>
    <div class="col-span-5 md:col-span-2 p-6 bg-gray-100 rounded-xl">
      <h1 class="mb-2 text-4xl font-semibold">{{ item.name }}</h1>
      <p class="mb-4 text-gray-600 font-semibold">Em {{ item.category.name }}</p>
      {% if item.briefing %}
        <div class="my-2 p-2 bg-gray-200/50 rounded-xl">
          {% for line in item.briefing.splitlines %}
            <p class="my-1 text-gray-800 font-semibold">&middot; {{ line }}</p>
          {% endfor %}
        </div>
      {% endif %}
      <div class="flex">
        <p class="text-green-500 text-5xl font-bold">R$ {{ item.price.amount }}</p>
        <a href="{{ whatsapp_call_link }}"
           target="_blank"
           rel="noopener noreferrer">
          <img src="{% static 'whatsapp.gif' %}"
               class="rounded-full mx-4"
               alt="Whatsapp" />
        </a>
      </div>
      {% if request.user.is_authenticated %}
        <div class="mt-6 p-2">
          <a href="{% url 'item:edit' item.id %}"
             class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Editar</a>
          <a href="{% url 'item:delete' item.id %}"
             class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Deletar</a>
        </div>
        {% comment %} {% else %}
        <a href="{% url 'conversation:new' item.id %}"
           class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a> {% endcomment %}
      {% endif %}
    </div>
  </div>
  <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
    {% if item.description %}
      <p class="text-gray-700">
        <strong class="text-gray-500">Descrição:</strong>
        <br />
      </p>
      {% for line in item.description.splitlines %}
        <p>
          {{ line }}
          <br />
        </p>
      {% endfor %}
      <br />
    {% endif %}
  </div>
  <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Itens relacionados</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      {% for item in related_items %}
        <div class="bg-gray-100 rounded-xl">
          <a href="{% url 'item:detail' item.id %}">
            <div class="flex items-center justify-center">
              <img src="{{ item.image_url }}"
                   {% comment %}
                   onerror="this.src='https://http.cat/404';"
                   {% endcomment %}
                   onerror="this.src='{% static "lupa.png" %}';"
                   alt="{{ item.name }}"
                   class="max-h-[40vh]" />
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ item.name }}</h2>
              <p class="text-green-500">R$: {{ item.price.amount }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

item/templates/item/form.html
{% extends "core/master.html" %}
{% block title %}
  {{ title }}
{% endblock title %}
{% block content %}
  <h1 class="mb-6 text-3xl">{{ title }}</h1>
  <form method="post" action="." enctype="multipart/form-data" name="file">
    {% csrf_token %}
    <div class="space-y-4">{{ form.as_p }}</div>
    {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}{{ field.errors }}{% endfor %}
        {{ form.non_field_errors }}
      </div>
    {% endif %}
    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
  </form>
{% endblock content %}

item/templates/item/items.html
{% extends "core/master.html" %}
{% load static %}
{% block title %}
    Busca
{% endblock title %}
{% block content %}
<h2 class="mb-6 text-2xl text-center">Busca</h2>
    <div class="p-3 md:grid md:grid-cols-4 md:gap-4 bg-gray-200 m-2 rounded-xl">
        <div class="col-span-1 rounded-xl bg-white p-3 md:sticky md:top-0 mb-4 md:mb-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="item_query"
                       class="w-full py-4 px-6 border rounded-xl mb-2"
                       type="text"
                       value="{{ item_query }}"
                       placeholder="O que procura?" />
                <button class="w-full py-1 px-8 text-lg bg-teal-500 text-white rounded-xl">Pesquisar</button>
            </form>
            <ul class="w-full">
                <li>
                    <a href="{% url 'item:items' %}"
                       class="w-full mt-2 py-1 px-8 inline-block text-lg bg-yellow-500 text-white text-center rounded-xl">Limpar filtros</a>
                </li>
            </ul>
            <hr class="my-6" />
            <div>
                <p class="font-semibold">Categories</p>
                <ul class="flex flex-wrap">
                    {% for category in categories %}
                        <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                            <a href="{% url 'item:items' %}?item_query={{ item_query }}&category_id={{ category.id }}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
                {% for item in items %}
                    <div class="rounded-xl bg-gray-100">
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="flex justify-center align-center">
                                <img src="{{ item.image_url }}" onerror="{% static "lupa.png" %};" class="max-h-[30vh]" />
                            </div>
                            <div class="p-4 bg-white rounded-b-xl">
                                <h2 class="text-xl">{{ item.name }}</h2>
                                <p class="text-green-500">R$: {{ item.price.amount }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}